### ISSUE TITLE
About 'Pubmed-shuffle-win-30. bin'

### ISSUE THREAD

**Issue by zlh-source** [EylonSho/LatentEntitiesExtraction#1]
Hello, thank you for your open source code, but the file _Pubmed-shuffle-win-30. bin_ cannot be downloaded now, could you please provide a copy?

**Comment by sy521** [comment]
do you get it ? I also want to get it . who can help me?2236229004@qq.com

**Comment by freexiduoduo** [comment]
hello, i also want to get it. can you help me? s20190702@xs.ustb.edu.cn
